---
- name: setup user account
  sudo: yes
  user: name={{ item }} state=present
  with_items:
     $usernames

# new users public keys must be committed to git.
- name: setup authorized_keys file for users
  sudo: yes
  authorized_key: user={{ item }} key="{{ lookup('file', item + 'Key.pub') }}"
  with_items:
    $usernames

- name: sudoers setup
  sudo: yes
  template: src=sudoers dest=/etc/sudoers validate='visudo -cf %s'
