- name: setup user accounts
  user: name={{ item }} state=present
  sudo: yes
  with_items:
    - corr
    - mbargar
    - jmadich
    - thanna

- name: setup authorized_keys file for users
  authorized_key: user={{ item }} key="{{ lookup('file', item + 'Key.pub') }}"
  sudo: yes
  with_items:
    - mbargar

- name: remove default accounts
  user: name=pi state=absent remove=yes
  sudo: yes
