---
- hosts: all
  sudo: yes
  vars_prompt:
    - name: "username"
      prompt: "Enter username"

    - name: "password"
      prompt: "Enter user's password"
      private: yes
      confirm: yes
      encrypt: sha512_crypt

  tasks:
    - name: setup user account
      user: name={{ username }} state=present password={{ password }}

  

