- name: Make sure web root directory is present
  file: path=/data/www state=directory
  sudo: yes
  when: usingVagrant is not defined

- name: Clean web root
  file: path=/data/www state=absent
  sudo: yes
  when: usingVagrant is not defined

# sshUser needs to be provided at the command line, it should match the value of the -u argument.
# We should be able to remove this variable once we're running ansible from a central server
# where the local username matches the remote username.
- name: recursively copy web assets from management server to target
  sudo: no
  local_action: command rsync -a ../www {{ sshUser }}@{{ inventory_hostname }}:/tmp
  when: usingVagrant is not defined

- name: copy web assets from tmp into web root
  sudo: yes
  command: cp -r /tmp/www /data
  when: usingVagrant is not defined

- name: clean web assets out of tmp
  file: path=/tmp/www state=absent
  sudo: yes
  when: usingVagrant is not defined

- name: Install nginx
  apt: pkg=nginx state=latest update_cache=yes
  sudo: yes

- name: Ensure nginx is started
  service: name=nginx state=started
  sudo: yes

- name: Disable default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  sudo: yes

- name: Remove default site
  file: path=/etc/nginx/sites-available/default state=absent
  sudo: yes

- name: Copy nginx global config
  copy: src=nginx/nginx.conf dest=/etc/nginx/nginx.conf backup=yes
  sudo: yes
  notify: 
    - reload nginx

- name: Update devcorr.com nginx server config
  copy: src=nginx/devcorrdotcom dest=/etc/nginx/sites-available
  sudo: yes

- name: Enable devcorr.com site
  file: path=/etc/nginx/sites-enabled/devcorrdotcom src=/etc/nginx/sites-available/devcorrdotcom state=link
  sudo: yes
  notify: 
    - reload nginx
