---
- name: install gulp-imagemin
  command: npm install gulp-imagemin
- name: install gulp-sass
  command: npm install gulp-sass
- name: install gulp-shell
  command: npm install gulp-shell
- name: install gulp-closure-compiler
  command: npm install gulp-closure-compiler
- name: install gulp-minify-css
  command: npm install gulp-minify-css  
- name: deploy via gulp  
  command: gulp